services:
  mysql:
    image: mysql:8.4
    container_name: hexagonal-architecture-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hexagonal_architecture
    ports:
      - "3306:3306"
    volumes:
      - hexagonal_mysql_data:/var/lib/mysql

volumes:
  hexagonal_mysql_data: